// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ygfnyswmiagjhiamrsfk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlnZm55c3dtaWFnamhpYW1yc2ZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0MzI1OTgsImV4cCI6MjA2OTAwODU5OH0.HglhIV6g1cTUe1jDpop7qHNHLOnDP_p6_F0Dnal_J_I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});